defaults:
  - override /hydra/sweeper: optuna

optimized_metric: val/macro_auprc

hydra:
  sweeper:
    direction: maximize
    n_trials: 120
    n_jobs: 4
    storage: sqlite:///optuna_redsm5.db
    study_name: redsm5_sweep
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
      n_startup_trials: 12
    params:
      model.model_name: choice(mental/mental-bert-base-uncased, microsoft/deberta-v3-base, answerdotai/ModernBERT-base, google/gemma-2-2b)
      model.pooling_strategy: choice(mean, first_k, last_k, attention_kv, attention_query)
      model.first_k: choice(64,128)
      model.last_k: choice(64,128)
      model.peft.enable_lora: choice(true,false)
      model.peft.lora_r: choice(8,16,32)
      model.peft.lora_alpha: choice(16,32,64)
      model.peft.lora_dropout: interval(0.0,0.1)
      data.max_len: choice(512,1024)
      train.batch_size: choice(8,16,32)
      train.grad_accum: choice(1,2,4)
      train.dropout: interval(0.0,0.3)
      train.lr: tag(log, interval(5e-6,3e-5))
      train.weight_decay: interval(0.0,0.2)
      train.scheduler: choice(linear,cosine)
      train.warmup_ratio: interval(0.0,0.2)
      train.loss.name: choice(bce,focal)
      train.loss.focal_gamma: choice(1.0,1.5,2.0)
      data.level: choice(sentence,post)
      data.agg.strategy: choice(max,attention)
      train.calib.method: choice(none,temp,isotonic)
