provider: gemini
model: gemini-1.5-pro
temperature: 0.0
top_p: 1.0
top_k: null
max_output_tokens: 1024
batch_size: 1
parallelism: 1
max_concurrency: 1
max_retries: 6
retry_base: 1.6
timeout_s: 60
json_mode: true
response_mime: application/json
sample_rate: 1.0
max_requests_per_minute: null
max_total_cost_usd: null
dry_run: false
fallback_to_mock: false
cache_uri: .cache/gemini_judgments.sqlite
vertex_enabled: false
vertex_project: null
vertex_location: null
vertex_model: null
jobs_path: ${data.path}/judge_jobs.jsonl
out_path: ${hydra:run.dir}/judgments_gemini.jsonl
log_path: ${hydra:run.dir}/judging_metrics.csv
api_key: ${env:GEMINI_API_KEY,}
