# configs/hpo/evidence_pairclf.yaml
study_name: "evidence_hpo"
n_trials: 80
timeout: 14400
sampler: "tpe"
pruner: "asha"
search_space:
  model_name: ["microsoft/deberta-v3-base","microsoft/deberta-v3-large","microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext","emilyalsentzer/Bio_ClinicalBERT"]
  lr: [1e-5, 3e-5, 5e-5, 6e-5]
  dropout: [0.0, 0.1, 0.2, 0.3]
  max_len: [192, 256, 384]
  loss: ["ce","focal"]
  pos_weight: [0.5, 1.0, 1.5, 2.0, 3.0]
objective: "macro_f1_present + 0.2*neg_precision - 0.5*ece"
